baseURL = 'https://andreasdelabie.github.io/narafi-ehbv'
languageCode = 'nl-BE'
title = 'Narafi EHBV'
theme = "hugo-theme-relearn-8.3.0"

[params]
    [params.search.page]
        disable = false
    [params.author]
        name = "Andreas Delabie"